name: semantic-search-system

services:
  postgres:
    container_name: pgvector
    image: pgvector/pgvector:pg17
    ports:
      - 54321:5432
    environment:
      - POSTGRES_USER=sssadmin
      - POSTGRES_PASSWORD=abc12345
      - POSTGRES_DB=projectdb
    volumes:
      - projectdb64:/var/lib/postgresql/data

  minio:
    container_name: minio1
    image: quay.io/minio/minio
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      - MINIO_ROOT_USER=ROOTUSER
      - MINIO_ROOT_PASSWORD=CHANGEME123
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"

  sss-backend:
    platform: linux/arm64
    build: 
      context: ./backend-go
      dockerfile: dockerfile
    container_name: sss-backend
    image: sss-backend:latest
    ports:
      - 3000:3000
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=sssadmin
      - DB_PASSWORD=abc12345
      - DB_NAME=projectdb
      - DB_SCHEMA=projectdb
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESS_KEY=ROOTUSER
      - MINIO_SECRET_KEY=CHANGEME123
      - MINIO_BUCKET=topics
    volumes:
      - sss_backend:/app/lib/
    depends_on:
      - postgres
      - minio
    restart: on-failure
  sss-frontend:
    platform: linux/arm64
    build: 
      context: .
      dockerfile: dockerfile
    container_name: sss-frontend
    image: sss-frontend:latest
    ports:
      - 80:80
    # environment:
    #   - VITE_BACKEND_URL=http://localhost:3000
    depends_on:
      - sss-backend

volumes:
  projectdb64:
  minio_data:
  sss_backend: